### ISSUE TITLE
Linken naar demo's zonder CSS en/of JS

### ISSUE THREAD

**Issue by KrijnHoetmer** [dvens/browser-technologies#1]
Tip voor het linken naar 'kale' demo's, zeker als je iets als PHP gebruikt. Voeg een extra query param toe aan je volledige demo, waarmee je CSS of JS uit kunt zetten. Iets als `?nojs` of `?nocss` in je URL, wat je dan kunt combineren tot `?nojs&nocss`. In je PHP kun je dan gewoon checken op `isset($_GET['nojs'])` en dan die tags niet uitschrijven. Voordeel is dan dat je niet meerdere versies van je code hoeft te onderhouden; zeker als je gaat doorontwikkelen wel handig als je één codebase hebt.

**Comment by dvens** [comment]
Het volgende werkt nu http://bt-2.djvens.nl/?nocss wanneer je geen css wilt tonen, http://bt-2.djvens.nl/?nojs wanneer je geen js wilt gebruiken en http://bt-2.djvens.nl/?nojs&nocss wanneer je zowel css als js uit wilt hebben.

**Comment by KoopReynders** [comment]
done
