### ISSUE TITLE
Scrollen op iOS werkt niet heel lekker

### ISSUE THREAD

**Issue by KrijnHoetmer** [dvens/browser-technologies#10]
Het voelt een beetje buggy aan. Ik denk door verschillende hacks met `height: 100%` en `overflow` (probeer zoveel mogelijk content in de natuurlijke flow te laten lopen).

Kijk ook naar de `backface-visibility: hidden;` hacks; zijn die echt nodig?

**Comment by dvens** [comment]
backface-visibility: hidden; was inderdaad niet nodig dit heb ik ook weggehaald. Het wordt voornamelijk gebruikt wanneer je gaat werken met 3d transforms. Ik heb de height 100% van de body en html afgehaald.

**Comment by KoopReynders** [comment]
done
