### ISSUE TITLE
"The groceries are saved in the browsers cookie"

### ISSUE THREAD

**Issue by KrijnHoetmer** [dvens/browser-technologies#2]
Well, actually... ;) Niet heel belangrijk voor je demo, maar toch. Ze worden server-side opgeslagen en PHP noemt dat een sessie. De enige manier waardoor PHP 'weet' welke sessie, is door een uniek cookie. Verwijder je dat cookie, dan zal PHP gewoon een nieuwe sessie aanmaken (en je oude lijstje 'vergeten'). Als ik exact hetzelfde cookie in mijn browser weet te krijgen, neem 'ik' gewoon die sessie van PHP over (zie ook 'Session hijacking').

`</386>`

**Comment by dvens** [comment]
Aangepast in de readme :)!

**Comment by KoopReynders** [comment]
done
