### ISSUE TITLE
Zoomen op (o.a.) een iPhone werkt niet

### ISSUE THREAD

**Issue by KrijnHoetmer** [dvens/browser-technologies#3]
`initial-scale=1, maximum-scale=1` is een doodzone voor toegankelijkheid, zelfs voor een goed ontworpen applicatie. Zie ook http://www.opera.com/blogs/mobile/2015/12/force-enable-zoom-opera-34-for-android/ (omdat zoveel developers dit verkeerd doen).

**Comment by dvens** [comment]
Aangepast naar: `<meta name="viewport" content="width=device-width, initial-scale=1">`. Het verteld te browser om de 'device-width' te gebruiken voor de website, en niet de website te schalen (de gebruiker kan hierdoor nog wel in/uit zoomen).

**Comment by KoopReynders** [comment]
done
