### ISSUE TITLE
Clearfix? :)

### ISSUE THREAD

**Issue by KrijnHoetmer** [dvens/browser-technologies#5]
Kleinigheidje, maar `<div class="cf"></div>` toevoegen aan je HTML voor een clearfix is natuurlijk ranzig ;) Waarschijnlijk omdat je floats wilde gebruiken voor meer browser support, maar vaak heb je door een element wel in de flow van je document te laten (in dit geval `.ingredients`) helemaal geen clearfix nodig. Probeer een clearfix dus ook te zien als code smell en ga op zoek naar een simpelere oplossing (vaak door wat CSS weg te halen).

**Comment by dvens** [comment]
Clearfix was niet nodig

**Comment by KoopReynders** [comment]
done
