### ISSUE TITLE
User agent sniffing voor column toggle

### ISSUE THREAD

**Issue by KrijnHoetmer** [dvens/browser-technologies#6]
Pas op met user agent sniffing, want dit gaat te snel stuk. Is dit niet iets wat je in CSS volledig met media queries kunt oplossen?

**Comment by dvens** [comment]
Ik heb de user sniffing weggehaald want dit kon inderdaad met media queries om de navigatie te togglen. Ik heb nu alleen native scrollTo gebruikt ipv. column toggle omdat het voor de nodige issues zorgde met scrollen. Ik heb hiervoor gebruik gemaakt van http://www.paulirish.com/2011/requestanimationframe-for-smart-animating/

**Comment by KoopReynders** [comment]
done
