### ISSUE TITLE
JS errors in IE8

### ISSUE THREAD

**Issue by KrijnHoetmer** [dvens/browser-technologies#7]
Je gebruikt feature detection, maar alsnog gaat er iets mis in IE8. Ik denk bij `[].slice.call()`, maar onderzoek dit ajb.

**Comment by dvens** [comment]
Ik heb de [].slice.call weggehaald en gewoon met een for loop door de items heen gelopen en zo een addeventlistener toegevoegd aan elk item, dit omdat for loop overal wel ondersteund wordt en ik dat niet een extra feature detection hoef te maken.

**Comment by KoopReynders** [comment]
done
