### ISSUE TITLE
Feature detect op `classList` ontbreekt

### ISSUE THREAD

**Issue by KrijnHoetmer** [dvens/browser-technologies#8]
Ook een kleinigheidje, maar in IE9 zou je errors kunnen krijgen door het gebruik van `classList`, zonder daarop te feature testen. Doordat `'draggable' in document.createElement('span')` al `false` is, loopt 'ie überhaupt niet door dat stuk script, maar pas hier wel mee op.

IE is trouwens de uitvinder van de Drag & Drop API, dus zeker IE9 zou grote delen hiervan wel moeten ondersteunen (het `draggable` bijvoorbeeld attribuut alleen niet). Mocht je het een interessante uitdaging vinden, kijk dan eens naar of je het ook werkend kunt krijgen in IE9.

**Comment by dvens** [comment]
Ik check voordat de app wordt opgestart nu op if('classList' in document.documentElement) als dit niet het geval is valt hij gewoon terug op de PHP versie. Ik kwam er niet echt uit met de Drag & Drop API in IE9.
