### ISSUE TITLE
Server en front-end niet in sync

### ISSUE THREAD

**Issue by KrijnHoetmer** [dvens/browser-technologies#9]
Doordat je in je drag & drop script bij het droppen `dropTarget.innerHTML` alleen gebruikt, weet de server natuurlijk niets van je sleep-actie. Hoe maak je je code nou zo dat je gebruik kunt maken van de logica op de server? Tip: hijack de submit, vang de response HTML op en plaats die in je lijst met ingrediënten (en je krijgt gratis de 'verwijder' functionaliteit per ingrediënt).

**Comment by dvens** [comment]
Het is gelukt server en front-end in sync te krijgen. Ik gebruik een xhttprequest om een post te doen naar naar de addItem.php. Wanneer de xhr niet wordt ondersteund (check ik met het volgende if('onload' in _xhr)) zal ik het formulier gewoon submit wanneer de drag geeindigd is. De response van de xhr plaats ik als innerhtml in de '.dropTarget'.

**Comment by KoopReynders** [comment]
done
